[build]
  publish = "."           # Your site files are in the root
  command = ""            # No build command needed for plain HTML

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "."        # Where your index.html lives
    prettyURLs = true
    trailingSlash = true